gnosis/prediction-market-agent

- prediction_market_agent/tools/web_scrape.py
No more of this:
```
/Users/evan/dev/prediction-market-agent/.venv/lib/python3.9/site-packages/langchain/__init__.py:29: UserWarning: Importing PromptTemplate from langchain root module is no longer supported. Please use langchain.prompts.PromptTemplate instead.
warnings.warn(
```
> Fix langchain import warning

- README.md
- agent.py
- main.py
- prediction_market_agent/data_models/market_data_models.py
- prediction_market_agent/markets/all_markets.py
I prefer `place_bet` taking a single required `amount` arg, and then handling the conversion to the correct currency, as apposed to taking optional `amount`s in all the possible currencies it could support.
> Pass in generic BetAmount to `place_bet`

- prediction_market_agent/deploy/deploy.py
- prediction_market_agent/deploy/utils.py
Using a http trigger for the cloud function causes failures when the scheduler tries to trigger the job. From what I could see this could be fixed by:
(1) switching to a pub/sub topic trigger for the function
(2) adding authentication to the scheduler
Couldn't see how to do (2) from the docs/googling, so have gone with (1)!
> Fix auth issue with function scheduler

- prediction_market_agent/agents/microchain_agent/functions.py
- prediction_market_agent/agents/microchain_agent/microchain_agent.py
- prediction_market_agent/agents/microchain_agent/utils.py
- tests/agents/test_microchain.py
Subclass microchain `Function` class with `MarketFunction` that takes `MarketType`, to differentiate behaviour of functions.
This way the abstractions in microchain_agent/functions.py don't have any market-specific code in them (i.e. no 'Omen' or 'Maninfold' imports from PMAT). There are few left over after the merge of https://github.com/gnosis/prediction-market-agent/pull/59, but the idea is there.
> Make microchain Functions (somewhat) market-type agnostic

- .github/workflows/python_ci.yaml
- prediction_market_agent/agents/microchain_agent/functions.py
- prediction_market_agent/agents/microchain_agent/microchain_agent.py
- tests/agents/test_microchain.py
Added test to ensure call args for all registered functions are correct.
> Fix GetWalletBalance.__call__ args

- prediction_market_agent/agents/microchain_agent/functions.py
- prediction_market_agent/agents/microchain_agent/utils.py
- tests/agents/test_microchain.py
- Remove existing `GetBalance` function
- Bit of refactoring to make `GetWalletBalance` market-agnostic
- Rename `GetWalletBalance` -> `GetBalance`
> GetWalletBalance -> GetBalance

- poetry.lock
- pyproject.toml
Requires relaxing python-dotenv in open-aea. Until [this](https://github.com/valory-xyz/open-aea/pull/740) PR is merged, a new release of open-aea is made, and this is included in mech-client, we can just point to forked versions of these repos here.
> Update crewai to latest release

- prediction_market_agent/agents/microchain_agent/app.py
- prediction_market_agent/agents/microchain_agent/functions.py
- prediction_market_agent/agents/microchain_agent/microchain_agent.py
- prediction_market_agent/agents/microchain_agent/omen_functions.py
- prediction_market_agent/agents/microchain_agent/utils.py
- tests/agents/microchain/test_functions.py
UI improvements:
- When the user hits enter after adding some reasoning, the agent executes immediatedly (saves an extra click on Run for the user)
- Remove misc functions `Sum` and `Product`. They aren't much use atm.
- Increase the verbosity of the redeem function. Before it returned None.
Fixes:
- `get_balance` should show both xdai and wxdai. Previously it was showing just xdai. If the agent placed a bet, it could show the balance not changing at all!
- Include all agent functions in dropdown list (see pic)
> Various improvements and fixes for microchain agent

- poetry.lock
- prediction_market_agent/agents/microchain_agent/market_functions.py
- pyproject.toml
Fixes the problem where, when you sell a position, due to small rounding errors, you are left with a tiny number of tokens. This shows up in subsequent `GetLiquidPositions` calls, which may be confusing for the agent!
☝️ this no longer happens after this PR
> Ignore tiny positions for microchain agent

- prediction_market_agent/agents/microchain_agent/app.py
- prediction_market_agent/agents/microchain_agent/deploy.py
- prediction_market_agent/agents/microchain_agent/microchain_agent.py
- scripts/deployed_general_agent_viewer.py
Currently the `Tool Usage` section of https://deployed-general-agent-viewer.ai.gnosisdev.com/ fails because the app doesn't have an openai api key in its env. It shouldn't need one, but it currently has to build a dummy agent (by calling `build_agent`).
By passing the api key in explicitly, instead of using `APIKeys()` internally, we can work around it by passing in a placeholder key
> Microchain `build_agent` should take openai api key argument

- prediction_market_agent/agents/microchain_agent/memory.py
- scripts/deployed_general_agent_viewer.py
e.g. `general-agent-1` has run for 50 iterations (1 session), but currently its metric shows 101 iterations!!
Before:
After:
> Fix 'iterations' metric in deployed agent viewer app

- prediction_market_agent/agents/microchain_agent/memory.py
- scripts/deployed_general_agent_viewer.py
- tests/test_chat_history.py
A more reliable way to cluster chat messages, which is especially useful if doing testing (where you might want to run sessions manually back-to-back, not have to re-configure time-between-sessions arg.
> Replace cluster_by_datetime with cluster_by_session on DatedChatHistory class

- prediction_market_agent/agents/microchain_agent/app.py
Functions names are still retrieved dynamically from the agent's engine on each call (so e.g. if a new Function is registered, it shows up), but without rebuilding functions.
Fixes https://github.com/gnosis/prediction-market-agent/issues/332
> Do not rebuild function list every general-agent app run

- prediction_market_agent/agents/think_thoroughly_agent/think_thoroughly_agent.py
Otherwise if `n_iterations` > 1, `scenarios_with_probs` will only contain the scenarios for the final iteration
> Add comment to exaplain `n_iterations` arg to `ThinkThoroughlyBase.answer_binary_market`

- prediction_market_agent/agents/think_thoroughly_agent/prompts.py
Tries to fix https://github.com/gnosis/prediction-market-agent/issues/357
Tried a few questions to reproduce the error, but was unable to 🤷. Giving this a go...
> Adjust 'PROBABILITY_CLASS_OUTPUT' prompt for ThinkThoroughly agent

- prediction_market_agent/agents/microchain_agent/prompts.py
Fixes https://github.com/gnosis/prediction-market-agent/issues/354
There may be many reasons for this, so we might need to re-open it if we see it again. For now, the only case I've been able to reproduce is where the agent calls a function without brackets (e.g. `GetMarkets` instead of `GetMarkets()`). This is parsed by `Agent.clean_reply` here https://github.com/galatolofederico/microchain/blob/main/microchain/engine/agent.py#L93 and becomes an empty string.
This change to the prompt fixes it.
From 10 tries before/after:
- before: 80% incorrect calls to GetMarkets, it does 3x retries always with the same error
- after: 70% correct calls to `GetMarkets()`/`GetBalance()`, always corrected the calls in the remaining 30% of cases (i.e. `GetMarkets` -> `GetMarkets()`
This could also be …
> Change agent's prompt to prevent it from replying with mis-formatted function call

- prediction_market_agent/agents/think_thoroughly_agent/think_thoroughly_agent.py
Fixes https://github.com/gnosis/prediction-market-agent/issues/357
crewai has this nice feature for parsing the output of a `Task` to a pydantic object that we weren't using 😀
> Fix json output parsing for the crew in ThinkThoroughlyWithItsOwnResearch.generate_prediction_for_one_outcome

- poetry.lock
- prediction_market_agent/agents/microchain_agent/microchain_agent.py
- pyproject.toml
- tests/agents/microchain/test_agent.py
Previously, deployed microchain agents might fail, but we wouldn't see this in our gcp logs as these errors were swallowed up in microchain. Now with https://github.com/galatolofederico/microchain/pull/15 it's possible to handle these errors. We now raise them ourselves.
In the prediction_market_agent/agents/microchain_agent/app.py they automatically appear nicely thanks to streamlit's nice handling of exceptions
> Raise errors from microchain agent

- prediction_market_agent/agents/microchain_agent/deploy.py
See an example where an agent runs for some number of iterations, but throws an exception:
On https://deployed-general-agent-viewer.ai.gnosisdev.com/ the agent's chat history is empty for that session, as the agent doesn't save its history up to the point of the exception
> Save microchain agent history even if an exception is thrown

- prediction_market_agent/agents/microchain_agent/prompts.py
- scripts/deployed_general_agent_viewer.py
The trader agent has a fixed prompt - no need to give it the ability to introspect its system prompt, or update it
> Do not register 'agent functions' for microchain trader agent

- prediction_market_agent/agents/known_outcome_agent/deploy.py
- prediction_market_agent/agents/prophet_agent/deploy.py
- prediction_market_agent/agents/think_thoroughly_agent/deploy.py
The motivation is to address https://github.com/gnosis/prediction-market-agent/issues/430, except:
1. we don't actually re-implement the strategy that prophet agents used).
2. we also bump the bet size of think-thoroughly agents to be inline with other deployed agents
For context:
> Set default bet size for various deployed agents to '1'

- scripts/llm_randomness.py
Unfortunately, it's more complex than we imagined @evangriffiths 😄 
I asked LLM to generate random numbers in a sequence. That's done 5x and the numbers at position `i` are plotted next to each other.
This is what we do mostly, we don't set the seed, but we set the temperature to 0:
Numbers are random after the first half. There is almost no consistency.
If we also set constant seed to 0, gpt-3.5-turbo and gpt-4 are almost good, but gpt-4-turbo and gpt-4o are still pretty random:
So the big question is, what happens if we set the temperature to some micro value? Well... gpt-4-turbo and gpt-4o are now pretty good. But gpt-3.5-turbo and gpt-4 are bad again! 
Interesting behaviour is with seed 0, but temperature 1. I expected randomness, but it's pretty consistent across all the models! 😱 …
> Small streamlit demo to test out LLM randomness

- prediction_market_agent/agents/microchain_agent/microchain_agent.py
Noticed deployed trader agents still had the ability to get and update their system prompt. Simple fix
> Use FunctionsConfig.include_agent_functions in build_agent_functions logic

- prediction_market_agent/agents/goal_manager.py
- prediction_market_agent/agents/microchain_agent/app.py
- prediction_market_agent/agents/microchain_agent/deploy.py
I forgot to add parent observation to general agent and now it looks like this, so fixing:
> Parent observations for general agent

- poetry.lock
- prediction_market_agent/agents/prophet_agent/deploy.py
- pyproject.toml
See comparison reports below - 'prophet with reasoning' appears to be a little bit better (i.e. lower MSE vs crowd prediction) than without reasoning. Not the motivation of this feature, but still a small bonus!
To reproduce:
```
git checkout evan/benchmark-prophet-with-same-research
python scripts/benchmark.py --n 30
```
> Deployable PredictionProphetAgents provide reasoning with their predictions

- poetry.lock
- prediction_market_agent/agents/known_outcome_agent/deploy.py
- prediction_market_agent/agents/prophet_agent/deploy.py
- prediction_market_agent/agents/think_thoroughly_agent/deploy.py
See simulation results in comment. For now, we take the highest simulated profit strategy for each agent, except for:
- DeployablePredictionProphetGPT4oAgent uses the 5th highest profit strategy (19% less profit for <50% less bet amount), because it has `bet_on_n_markets_per_run = 20` so its profitability is constrained more by how many bets it can make in parallel
- DeployableThinkThoroughlyProphetResearchAgent uses second highest profit strategy because it is verrry close to the highest profit strategy but has a significantly lower bet amount
If we change agents to have a larger `bet_on_n_markets_per_run`, we should also consider using the betting strategy with max ROI/capital efficiency instead.
> Update DeployableTraderAgent betting stategies for max profit, based on historical simulations

- prediction_market_agent/agents/goal_manager.py
- prediction_market_agent/agents/microchain_agent/deploy.py
- tests/agents/test_goal_manager.py
Currently there is not much variety in the goals generated by the goal manager.
This is because, when generating a new goal:
- goal manager has `self.retry_limit = N`
- goal is evaluated as having failed N times
- the goal manager only pulls in the past N goals, and they are all the same (failed) goal!
- so it has no visibility of earlier goals
- so generates a new goal that is very similar to earlier ones
The fixes are the following:
- Add new `goal_history_limit` property to `GoalManager`
- Pull in more goals when generating a new goal
- Only pull in unique past goals so the goal history is not filled with repeated failed goals
> Make goal manager create more varied goals

- prediction_market_agent/agents/microchain_agent/deploy.py
We are still getting `essage: "{"detail":"E1002 PromptTooLong: Prompt length exceeds maximum input length"}"`, these general agents probably need a more clever, general fix.
> Only 10 iterations for Llama agent

- prediction_market_agent/agents/invalid_agent/deploy.py
- prediction_market_agent/run_agent.py
Currently there is one invalid market live:
[Will JD Vance be publicly accused of a sex crime before October 15?](https://presagio.pages.dev/markets?id=0x4256da91466b6fdc8e0d29efddc35af6edb8854e) with p_yes 19%.
> Add InvalidAgent

- prediction_market_agent/agents/think_thoroughly_agent/deploy.py
- prediction_market_agent/agents/think_thoroughly_agent/think_thoroughly_agent.py
I think we can safely make think thoroughly prophet cheaper, by using gpt 4o on its prophet-research part.
Looking at Dune, gpt-4o prophet agent is among the best:
So if we switch to 4o only in the prophet-research part, it should still be good (if not better).
> Cheaper think thoroughly prophet agent

- prediction_market_agent/agents/microchain_agent/nft_treasury_game/app_nft_treasury_game.py
- prediction_market_agent/db/long_term_memory_table_handler.py
- prediction_market_agent/db/sql_handler.py
A few changes:
- background switching between messages
- reasoning not shown as function calls
- Function Call + Function Response merged into a single message
> Make nft web app nicer

- prediction_market_agent/agents/microchain_agent/nft_treasury_game/app_nft_treasury_game.py
- prediction_market_agent/db/agent_communication.py
- prediction_market_agent/db/long_term_memory_table_handler.py
- prediction_market_agent/db/sql_handler.py
> Add pagination to treasury app

- prediction_market_agent/agents/microchain_agent/prompts.py
Related to https://github.com/gnosis/prediction-market-agent/issues/647, the fact that the errored function call isn't in the history is a feature of Microchain, not a bug. 
We could refactor it a bit, but atm I'm not convinced that it has to change, so I did a "2025 programmers move" -- just ask the LLM to do it for us! 😄 For our needs it seems to work fine.
> Show errored function in reasoning

- prediction_market_agent/agents/microchain_agent/nft_treasury_game/scripts/generate_report.py
- prediction_market_agent/db/models.py
- prediction_market_agent/db/report_table_handler.py
- prediction_market_agent/run_reset_game.py
-> Improved summary prompts, now displaying useful information
-> Storing reports in the DB instead of inside a file - it's a lot easier to query the DB afterwards then to ssh into a running container and `cat` the contents of the file.
-> PS - In the report below, the LLM outputs the agent address sometimes (instead of the identifier). This can be fixed later, we are mostly interested in the key transfers, value etc which are printed.
```
agent_id                     xdai_difference    nft_balance_end
-------------------------  -----------------  -----------------
nft-treasury-game-agent-1               0.02                  1
nft-treasury-game-agent-2              12.01                  0
nft-treasury-game-agent-3               0.03                  1
nft-treasury-game-agent-4 …
```
> Storing report in the DB instead of writing to file

- prediction_market_agent/agents/microchain_agent/nft_treasury_game/app_nft_treasury_game.py
- prediction_market_agent/agents/microchain_agent/nft_treasury_game/deploy_nft_treasury_game.py
- prediction_market_agent/run_reset_game.py
> More NFT game mods

- prediction_market_agent/agents/safe_guard_agent/safe_utils.py
These flows currently work:
- send a signed message 
- sign & execute transaction (ie if Safe Guard's signature is last required and it can execute the transaction immediately)
- sign & post transaction
- sign & uploaded transaction with the new signer
What's broken:
- Safe UI in case that we upload transaction with Safe sign, see https://ethereum.stackexchange.com/questions/168598/queued-transactions-in-safe-ui-giving-500-internal-server-error for details.
To reproduce the error:
1. Create a fresh Safe (really, create a new one; it will get broken!) with three required signers (your EOA, another Safe with threshold 1, where you have another EOA as signer and a third one that doesn't matter)
2. Send tiny xDai to it
3. Create a transaction to send even tiner xDai to somewhere else
4. Add …
> Add support of nested Safes in Safe Guard Agent

- .gitignore
- prediction_market_agent/development_tools/prophet_agent_tester.py
- prediction_market_agent/development_tools/test_all_prophet_agents.py
- prediction_market_agent/development_tools/test_single_agent.py
* Agents for prophet need to be moved to PMA because of cyclic dependency
See also:
https://github.com/gnosis/prediction-market-agent-tooling/pull/730
> Moved ProphetAgent benchmarks from PMAT

- prediction_market_agent/agents/replicate_to_omen_agent/omen_replicate.py
If fund removal fails for one market it should not affect other-ones.
> If fund removal fails for one market  processing should continue

- prediction_market_agent/agents/berlin1_agent/polysent_agent.py
- prediction_market_agent/agents/berlin2_agent/openai_search_agent_high.py
- prediction_market_agent/agents/prophet_agent/deploy.py
- prediction_market_agent/agents/think_thoroughly_agent/deploy.py
TODO: Check profits in 1 month, have a slack reminder already ✅ 
Details:
Number of bets since 2025-05-14 00:00:00+00:00: 392
139 bets do not have a corresponding trace (26.18%), ignoring them.
Early stopping detected. No improvement at current_trial_number=513, after early_stopping_rounds=500.
[3 / 5] Best value for Berlin1PolySentAgent (params: {'strategy_name': 'SimpleCategoricalKellyBettingStrategy', 'bet_amount': 1.1433268859524697}, n train bets: 186, n test bets: 101): Training maximization: [0.03796308050481241, 1.3076385476108756, -0.8721291401200706] (no. 13)Testing profit: 1.04 Original profit on Testing: 0.10 (testing dates 2025-07-14 to 2025-07-20)
Early stopping detected. No improvement at current_trial_number=500, after early_stopping_rounds=500.
[4 / 5] Best value for …
> New strategies
