gnosis/prediction-market-agent

poetry.lock, prediction_market_agent/agents/microchain_agent/README.md, prediction_market_agent/agents/microchain_agent/app.py, prediction_market_agent/agents/microchain_agent/deploy.py, prediction_market_agent/agents/microchain_agent/functions.py, prediction_market_agent/agents/microchain_agent/microchain_agent.py, prediction_market_agent/agents/microchain_agent/utils.py, prediction_market_agent/run_agent.py, prediction_market_agent/streamlit_utils.py, prediction_market_agent/utils.py, pyproject.toml
Allows the user to interact with the agent via iterative execution of the agent for a configurable number of steps, interleaved with user-input reasoning.
=> Add microchain agent app

prediction_market_agent/agents/microchain_agent/app.py, prediction_market_agent/agents/microchain_agent/utils.py
Two small improvements:
1. Display the agent's history after each iteration, as apposed to at the end of all iterations
2. Grey out the `model` selection box once the agent has been initialized (once the first run is triggered)
=> Microchain streamlit app improvements

poetry.lock, prediction_market_agent/agents/microchain_agent/functions.py, pyproject.toml, tests/agents/microchain/test_functions.py
Change `GetPositions` -> `GetLiquidPositions` to reflect its description+implementation better. Now prevents the user from trying to sell positions on markets that have closed.
=> Update microchain function for getting positions

prediction_market_agent/agents/microchain_agent/app.py, prediction_market_agent/agents/microchain_agent/functions.py
Evidence of the agent chat history from the app being written to the DB:
=> Add long term memory to microchain agent app

prediction_market_agent/agents/microchain_agent/functions.py, prediction_market_agent/agents/microchain_agent/memory.py, prediction_market_agent/db/db_storage.py, tests/db/test_db_storage.py
Fixes https://github.com/gnosis/prediction-market-agent/issues/185
=> Change LongTermMemory.search to take datetime filtering args

prediction_market_agent/agents/microchain_agent/functions.py, prediction_market_agent/agents/microchain_agent/memory.py, prediction_market_agent/agents/microchain_agent/microchain_agent.py, prediction_market_agent/agents/microchain_agent/utils.py, tests/agents/microchain/test_functions.py
Example using gpt4o from the past 24hours of memories from users of https://autonomous-trader-agent.streamlit.app/:
```
**Past Learnings:**
1. **Market Assessment:** 
- **Action:** Retrieved a list of prediction markets.
- **Learning:** Assess the probability of each event occurring to determine which tokens are undervalued or overvalued.
2. **Probability Prediction:**
- **Action:** Predicted probabilities for specific markets.
- **Learning:** 
- DJI Pocket 3 release probability is 100% (fully priced).
- Ceasefire between Israel and Hamas probability is 65% (potentially undervalued).
3. **Trading Decisions:**
- **Action:** Bought Yes outcome tokens for the ceasefire market.
- **Learning:** Continue to assess other markets for potential trades.
**Past Learnings:**
1. **Market Probability …
```
=> Use `memories_to_learnings` in `RememberPastLearnings` microchain function

prediction_market_agent/agents/autogen_general_agent/deploy.py, prediction_market_agent/agents/autogen_general_agent/prompts.py, prediction_market_agent/agents/autogen_general_agent/social_agent.py, prediction_market_agent/agents/autogen_general_agent/social_media/abstract_handler.py, prediction_market_agent/agents/autogen_general_agent/social_media/farcaster_handler.py, prediction_market_agent/agents/autogen_general_agent/social_media/twitter_handler.py, prediction_market_agent/agents/utils.py
closes #221 
-> Makes tweets more analytical
-> Adds quote tweet/cast functionality
=> 221 place more emphasis on reasoning when tweetingcasting

prediction_market_agent/agents/microchain_agent/app.py
Fixes https://github.com/gnosis/prediction-market-agent/issues/241
=> Fix balance lag in microchain app

prediction_market_agent/agents/microchain_agent/call_api.py, prediction_market_agent/agents/microchain_agent/microchain_agent.py
=> #271 issue: Add call API function to general agent

poetry.lock, pyproject.toml, scripts/metaculus_bot_tournament.py
A script that uses ThinkThoroughlyAgent that makes predictions for metaculus bot prediction competition markets, see  https://www.metaculus.com/project/ai-benchmarking-warmup/?status=open
=> Metaculus bot prediction script

prediction_market_agent/agents/metaculus_agent/deploy.py
Committed an unintended local change 🤦
=> DeployableMetaculusBotTournamentAgent bugfix

prediction_market_agent/agents/microchain_agent/memory.py, scripts/deployed_general_agent_viewer.py
Otherwise you are met with an unwelcoming screen
=> Ensure streamlit app for deployed agent viewer runs without error if history is empty

prediction_market_agent/agents/microchain_agent/blockchain/code_interpreter.py, prediction_market_agent/agents/microchain_agent/blockchain/contract_class_converter.py, prediction_market_agent/agents/microchain_agent/blockchain/models.py, prediction_market_agent/agents/microchain_agent/microchain_agent.py, tests/agents/microchain/conftest.py, tests/agents/microchain/test_contract_class_converter.py
-> Added wxDAI functions to 'build_functons' call on Streamlit
=> 329 register solidity python functions on general agent wxdai

prediction_market_agent/agents/microchain_agent/call_api.py, prediction_market_agent/utils.py
=> Telegram function

prediction_market_agent/agents/think_thoroughly_agent/think_thoroughly_agent.py, prediction_market_agent/utils.py, tests/test_utils.py
Fixes https://github.com/gnosis/prediction-market-agent/issues/384
=> Disable crewai telemetry

prediction_market_agent/agents/known_outcome_agent/known_outcome_agent.py, prediction_market_agent/agents/llamaindex_agent.py, prediction_market_agent/agents/microchain_agent/market_functions.py, prediction_market_agent/agents/microchain_agent/microchain_agent.py, prediction_market_agent/agents/prophet_agent/deploy.py, prediction_market_agent/ai_models/openai_ai_models.py, prediction_market_agent/run_agent.py, prediction_market_agent/tools/web_scrape/basic_summary.py, prediction_market_agent/utils.py, scripts/agent_app.py, scripts/deployed_general_agent_viewer.py
Through the API, these models are cheaper and perform better
=> Retire gpt3.5 agents, replace with gpt4o

prediction_market_agent/agents/microchain_agent/deploy.py
So we don't make unnecessary DB writes
=> Only save microchain agent system prompt if modified

prediction_market_agent/db/pinecone_handler.py
Reverts gnosis/prediction-market-agent#411
=> Revert "Remove TQDM inside of agents, because of logs in GCP"

poetry.lock, prediction_market_agent/utils.py, pyproject.toml, scripts/agent_app.py
When I tried it locally, after a few predictions, now I ended up at 1.8 GB memory instead of 2.8 GB. I think 1.8 is still too much, but I wasn't able to figure it out yet. So at least something.
=> Streamlit fixes

scripts/deployed_general_agent_viewer.py
=> Add session iterations to expanders in deployed general agent viewer

.gitignore
This file is needed for `streamlit run scripts/monitor_app.py`
=> Add .env.monitor to .gitignore

scripts/deployed_general_agent_viewer.py
For 'general agent'
For 'trader agent'
=> In deployed agent viewer build function list based on sysprompt

prediction_market_agent/agents/known_outcome_agent/deploy.py
Part of https://github.com/gnosis/prediction-market-agent/issues/480
=> Return reasoning in DeployableKnownOutcomeAgent.answer_binary_market

prediction_market_agent/agents/known_outcome_agent/deploy.py, prediction_market_agent/agents/prophet_agent/deploy.py, prediction_market_agent/agents/think_thoroughly_agent/deploy.py
It seems like we are doing fine on OpenAI (50% of the budget used last month) and Tavily (it doesn't show last month's usage, but currently on 7k out of 38k credits).
Shall we bet a bit more?
=> Bet on more markets

.github/workflows/python_cd.yaml, poetry.lock, pyproject.toml
=> Optional build in PR

prediction_market_agent/agents/microchain_agent/balance_functions.py, prediction_market_agent/agents/microchain_agent/microchain_agent.py, prediction_market_agent/agents/microchain_agent/nft_treasury_game/app_nft_treasury_game.py, prediction_market_agent/agents/microchain_agent/nft_treasury_game/deploy_nft_treasury_game.py, prediction_market_agent/agents/microchain_agent/prompts.py, prediction_market_agent/db/blockchain_transaction_fetcher.py
=> More interesting prompts for NFT agents

prediction_market_agent/agents/microchain_agent/nft_treasury_game/app_nft_treasury_game.py, prediction_market_agent/agents/microchain_agent/nft_treasury_game/messages_functions.py
=> Waiting function for NFT agent

poetry.lock, pyproject.toml
=> Updated wallet version

prediction_market_agent/agents/microchain_agent/memory_functions.py, prediction_market_agent/agents/utils.py
Before:
After:
Hopefully it's not just confirmation bias, but I think it's less generic and more future-planing-like.
=> Add optional question to process memories

prediction_market_agent/agents/prophet_agent/deploy.py
Hot fix for https://github.com/gnosis/prediction-market-agent/issues/729, it's not consistent so we can keep him running for markets where it success
=> Prophet just_warn_on_unexpected_model_behavior in R1

prediction_market_agent/agents/safe_guard_agent/app.py, prediction_market_agent/agents/safe_guard_agent/guards/llm.py, prediction_market_agent/agents/safe_guard_agent/safe_api_models/detailed_transaction_info.py, prediction_market_agent/agents/safe_guard_agent/safe_api_models/transactions.py, prediction_market_agent/agents/safe_guard_agent/safe_api_utils.py, prediction_market_agent/agents/safe_guard_agent/safe_guard.py, prediction_market_agent/agents/safe_guard_agent/safe_utils.py
A few issues after this PR:
- https://github.com/gnosis/prediction-market-agent/issues/769
- https://github.com/gnosis/prediction-market-agent/issues/770
=> Safe Guard without signing + fix models

.gitignore, prediction_market_agent/agents/microchain_agent/microchain_agent.py, prediction_market_agent/agents/microchain_agent/nft_treasury_game/app_nft_treasury_game.py, prediction_market_agent/agents/microchain_agent/nft_treasury_game/contracts.py, prediction_market_agent/agents/microchain_agent/nft_treasury_game/scripts/README.md, prediction_market_agent/agents/microchain_agent/nft_treasury_game/scripts/add_new_round.py, prediction_market_agent/agents/microchain_agent/nft_treasury_game/scripts/reset_balance_anvil.py, prediction_market_agent/agents/microchain_agent/nft_treasury_game/scripts/run_reset_game.py, prediction_market_agent/agents/microchain_agent/sql/clean_data.sql, prediction_market_agent/agents/microchain_agent/sql/export_data.py
=> NFT Game Adjustments

prediction_market_agent/agents/berlin1_agent/polysent_agent.py, prediction_market_agent/agents/berlin2_agent/openai_search_agent_high.py, prediction_market_agent/agents/berlin2_agent/openai_search_agent_variable.py, prediction_market_agent/agents/gptr_agent/deploy.py, prediction_market_agent/agents/prophet_agent/deploy.py
Reverts gnosis/prediction-market-agent#927 because of bug found in the betting optimization script
=> Revert "Update betting strategies based on benchmark"

prediction_market_agent/agents/replicate_to_omen_agent/omen_replicate.py, prediction_market_agent/db/replicated_markets_table_handler.py
Closes https://github.com/gnosis/prediction-market-agent/issues/936
=> not replicating known markets

prediction_market_agent/agents/arbitrage_agent/data_models.py, prediction_market_agent/agents/arbitrage_agent/deploy.py
Fixes: https://github.com/gnosis/prediction-market-agent/issues/946
=> Fixed arbitrage agent loosing money
